name: CI/CD Workflow

on:
  workflow_dispatch:
    inputs:
      run_terraform:
        description: 'Run Terraform Stage'
        required: true
        default: 'false'
        type: choice
        options:
          - 'true'
          - 'false'
      run_docker_image:
        description: 'Run Docker Image Stage'
        required: true
        default: 'false'
        type: choice
        options:
          - 'true'
          - 'false'
      run_kustomize:
        description: 'Run Kustomize Stage'
        required: true
        default: 'false'
        type: choice
        options:
          - 'true'
          - 'false'

jobs:
  terraform:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.run_terraform == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Initialize Terraform
        run: terraform init

      - name: Apply Terraform
        run: terraform apply -auto-approve

  docker_image:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.run_docker_image == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image
        run: docker build -t my-app:latest .

      - name: Push Docker Image
        run: docker push my-app:latest

  kustomize:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.run_kustomize == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Kustomize
        run: |
          curl -s https://api.github.com/repos/kubernetes-sigs/kustomize/releases/latest \
          | grep browser_download_url \
          | grep linux_amd64 \
          | cut -d '"' -f 4 \
          | xargs curl -LO
          mv kustomize_v*_linux_amd64 kustomize
          chmod +x kustomize
          sudo mv kustomize /usr/local/bin/

      - name: Apply Kustomize
        run: kustomize build ./k8s | kubectl apply -f -
